import { formatDate } from "@/lib/utils";
import { LatestTrips, LatestUser, Stat, Trip } from "./types";

export const stats: Stat[] = [
  {
    title: "total users",
    amount: 12450,
    trend: "up",
  },
  {
    title: "total trips",
    amount: 3210,
    trend: "down",
  },
  {
    title: "active users today",
    amount: 520,
    trend: "up",
  },
];

export const trips: Trip[] = [
  {
    id: 1,
    title: "Eko Hotels",
    location: "Highland street, Lagos",
    imgUrl: "/assets/images/sample.jpeg",
    tags: ["Mountains", "City"],
    price: 300,
  },
  {
    id: 2,
    title: "Millenium Hotels",
    location: "Lowland, Nigeria",
    imgUrl: "/assets/images/sample1.jpg",
    tags: ["Solo Travel", "Budget"],
    price: 790,
  },
  {
    id: 3,
    title: "High towers park",
    location: "Port Harcourt, Rivers State",
    imgUrl: "/assets/images/sample2.jpg",
    tags: ["Luxury", "Beach"],
    price: 870,
  },
  {
    id: 4,
    title: "Grills in Uyo",
    location: "Akwa Ibom, Nigeria",
    imgUrl: "/assets/images/sample3.jpg",
    tags: ["Sports", "Adventurous"],
    price: 870,
  },
];

export const latestUsers: LatestUser[] = [
  {
    name: "James Anderson",
    imgUrl: "/assets/images/james.webp",
    itenaries: 12,
  },
  {
    name: "Michael Johnson",
    imgUrl: "/assets/images/michael.webp",
    itenaries: 21,
  },
  {
    name: "David Brown",
    imgUrl: "/assets/images/david.webp",
    itenaries: 15,
  },
  {
    name: "Orlando Diggs",
    imgUrl: "/assets/images/james.webp",
    itenaries: 26,
  },
];

export const latestTrips: LatestTrips[] = [
  {
    name: "Lagos Island",
    imgUrl: "/assets/images/sample1.jpg",
    fromDate: "Jun 02",
    toDate: "June 12",
  },
  {
    name: "Port Harcourt Beach",
    imgUrl: "/assets/images/sample2.jpg",
    fromDate: "Jun 02",
    toDate: "Jun 12",
  },
  {
    name: "Calabar Carnival",
    imgUrl: "/assets/images/sample3.jpg",
    fromDate: "Jun 02",
    toDate: "Jun 12",
  },
  {
    name: "Eko Hotels",
    imgUrl: "/assets/images/sample4.jpg",
    fromDate: "Jun 02",
    toDate: "Jun 12",
  },
];

export const allTrips = [
  {
    id: 1,
    title: "Eko Hotels",
    location: "Highland street, Lagos",
    imgUrl: "/assets/images/sample3.jpg",
    tags: ["Mountains", "City"],
    price: 300,
  },
  {
    id: 2,
    title: "Millennium Hotels",
    location: "Lowland, Nigeria",
    imgUrl: "/assets/images/sample7.jpg",
    tags: ["Solo Travel", "Budget"],
    price: 790,
  },
  {
    id: 3,
    title: "High Towers Park",
    location: "Port Harcourt, Rivers State",
    imgUrl: "/assets/images/sample1.jpg",
    tags: ["Luxury", "Beach"],
    price: 870,
  },
  {
    id: 4,
    title: "Grills in Uyo",
    location: "Akwa Ibom, Nigeria",
    imgUrl: "/assets/images/sample2.jpg",
    tags: ["Sports", "Adventurous"],
    price: 870,
  },
  {
    id: 5,
    title: "Tropical Bay Resort",
    location: "Badagry, Lagos",
    imgUrl: "/assets/images/sample5.jpg",
    tags: ["Beach", "Romantic"],
    price: 1200,
  },
  {
    id: 6,
    title: "Savannah Suites",
    location: "Abuja, FCT",
    imgUrl: "/assets/images/sample6.jpg",
    tags: ["Business", "Luxury"],
    price: 950,
  },
  {
    id: 7,
    title: "Obudu Mountain Resort",
    location: "Obudu, Cross River",
    imgUrl: "/assets/images/sample8.jpg",
    tags: ["Mountains", "Adventure"],
    price: 1100,
  },
  {
    id: 8,
    title: "Lush Garden Villas",
    location: "Enugu, Nigeria",
    imgUrl: "/assets/images/sample4.jpg",
    tags: ["Nature", "Relaxation"],
    price: 600,
  },
  {
    id: 9,
    title: "The Palms Stay",
    location: "Victoria Island, Lagos",
    imgUrl: "/assets/images/sample1.jpg",
    tags: ["City", "Luxury"],
    price: 1350,
  },
  {
    id: 10,
    title: "Eco Valley Camp",
    location: "Ijebu Ode, Ogun State",
    imgUrl: "/assets/images/sample2.jpg",
    tags: ["Camping", "Eco-Friendly"],
    price: 480,
  },
  {
    id: 11,
    title: "Heritage Lodge",
    location: "Ibadan, Oyo State",
    imgUrl: "/assets/images/sample7.jpg",
    tags: ["Cultural", "Budget"],
    price: 370,
  },
  {
    id: 12,
    title: "Ocean Breeze Hotel",
    location: "Lekki, Lagos",
    imgUrl: "/assets/images/sample6.jpg",
    tags: ["Beach", "Nightlife"],
    price: 950,
  },
  {
    id: 13,
    title: "Peaceful Pines Resort",
    location: "Jos, Plateau State",
    imgUrl: "/assets/images/sample3.jpg",
    tags: ["Mountains", "Retreat"],
    price: 710,
  },
  {
    id: 14,
    title: "Luxury Sands Hotel",
    location: "Asaba, Delta State",
    imgUrl: "/assets/images/sample4.jpg",
    tags: ["Luxury", "Family"],
    price: 990,
  },
  {
    id: 15,
    title: "Serenity Resort",
    location: "Lokoja, Kogi State",
    imgUrl: "/assets/images/sample5.jpg",
    tags: ["Nature", "Relaxation"],
    price: 520,
  },
  {
    id: 16,
    title: "Maple Comfort Inn",
    location: "Abeokuta, Ogun State",
    imgUrl: "/assets/images/sample2.jpg",
    tags: ["Solo Travel", "Budget"],
    price: 430,
  },
  {
    id: 17,
    title: "Sunset Peak Lodge",
    location: "Makurdi, Benue State",
    imgUrl: "/assets/images/sample8.jpg",
    tags: ["Hiking", "Viewpoints"],
    price: 890,
  },
  {
    id: 18,
    title: "Golden Horizon",
    location: "Calabar, Cross River",
    imgUrl: "/assets/images/sample1.jpg",
    tags: ["Culture", "Beach"],
    price: 870,
  },
  {
    id: 19,
    title: "Coastal Haven Hotel",
    location: "Warri, Delta State",
    imgUrl: "/assets/images/sample6.jpg",
    tags: ["Romantic", "Seaside"],
    price: 1140,
  },
  {
    id: 20,
    title: "Tranquil Trails Resort",
    location: "Ado-Ekiti, Ekiti State",
    imgUrl: "/assets/images/sample3.jpg",
    tags: ["Nature", "Hiking"],
    price: 760,
  },
];

export const allUsers = [
  {
    name: "Lena Carter",
    email: "lena.carter@example.com",
    imgUrl: "/assets/images/james.webp",
    itenaries: 5,
    dateJoined: formatDate("2024-03-12"),
    status: "user",
  },
  {
    name: "Omar Bennett",
    email: "omar.bennett@example.com",
    imgUrl: "/assets/images/james.webp",
    itenaries: 3,
    dateJoined: formatDate("2023-11-06"),
    status: "admin",
  },
  {
    name: "Mia Rodriguez",
    email: "mia.rodriguez@example.com",
    imgUrl: "/assets/images/james.webp",
    itenaries: 8,
    dateJoined: formatDate("2024-07-18"),
    status: "user",
  },
  {
    name: "Ethan Moore",
    email: "ethan.moore@example.com",
    imgUrl: "/assets/images/james.webp",
    itenaries: 2,
    dateJoined: formatDate("2023-09-27"),
    status: "user",
  },
  {
    name: "Zara Khan",
    email: "zara.khan@example.com",
    imgUrl: "/assets/images/james.webp",
    itenaries: 10,
    dateJoined: formatDate("2023-12-30"),
    status: "admin",
  },
  {
    name: "Noah Kim",
    email: "noah.kim@example.com",
    imgUrl: "/assets/images/james.webp",
    itenaries: 7,
    dateJoined: formatDate("2024-01-22"),
    status: "user",
  },
  {
    name: "Sophie Green",
    email: "sophie.green@example.com",
    imgUrl: "/assets/images/james.webp",
    itenaries: 0,
    dateJoined: formatDate("2023-04-14"),
    status: "user",
  },
  {
    name: "Isaac Lee",
    email: "isaac.lee@example.com",
    imgUrl: "/assets/images/james.webp",
    itenaries: 12,
    dateJoined: formatDate("2024-09-10"),
    status: "admin",
  },
  {
    name: "Chloe Walker",
    email: "chloe.walker@example.com",
    imgUrl: "/assets/images/james.webp",
    itenaries: 6,
    dateJoined: formatDate("2024-06-25"),
    status: "user",
  },
  {
    name: "Liam Murphy",
    email: "liam.murphy@example.com",
    imgUrl: "/assets/images/james.webp",
    itenaries: 11,
    dateJoined: formatDate("2023-08-08"),
    status: "user",
  },
  {
    name: "Ava Thomas",
    email: "ava.thomas@example.com",
    imgUrl: "/assets/images/james.webp",
    itenaries: 4,
    dateJoined: formatDate("2024-11-15"),
    status: "user",
  },
  {
    name: "Daniel Wilson",
    email: "daniel.wilson@example.com",
    imgUrl: "/assets/images/james.webp",
    itenaries: 9,
    dateJoined: formatDate("2023-06-01"),
    status: "admin",
  },
  {
    name: "Emily Johnson",
    email: "emily.johnson@example.com",
    imgUrl: "/assets/images/james.webp",
    itenaries: 3,
    dateJoined: formatDate("2024-02-10"),
    status: "user",
  },
  {
    name: "Lucas Scott",
    email: "lucas.scott@example.com",
    imgUrl: "/assets/images/james.webp",
    itenaries: 0,
    dateJoined: formatDate("2023-10-03"),
    status: "user",
  },
  {
    name: "Aria Patel",
    email: "aria.patel@example.com",
    imgUrl: "/assets/images/james.webp",
    itenaries: 14,
    dateJoined: formatDate("2024-04-09"),
    status: "admin",
  },
  {
    name: "Henry Adams",
    email: "henry.adams@example.com",
    imgUrl: "/assets/images/james.webp",
    itenaries: 1,
    dateJoined: formatDate("2023-05-27"),
    status: "user",
  },
  {
    name: "Natalie Evans",
    email: "natalie.evans@example.com",
    imgUrl: "/assets/images/james.webp",
    itenaries: 13,
    dateJoined: formatDate("2023-07-20"),
    status: "user",
  },
  {
    name: "Jack Turner",
    email: "jack.turner@example.com",
    imgUrl: "/assets/images/james.webp",
    itenaries: 5,
    dateJoined: formatDate("2024-10-11"),
    status: "admin",
  },
  {
    name: "Lily Martin",
    email: "lily.martin@example.com",
    imgUrl: "/assets/images/james.webp",
    itenaries: 6,
    dateJoined: formatDate("2024-08-02"),
    status: "user",
  },
  {
    name: "Nathan Hall",
    email: "nathan.hall@example.com",
    imgUrl: "/assets/images/james.webp",
    itenaries: 15,
    dateJoined: formatDate("2023-03-18"),
    status: "user",
  },
];
